---
- hosts: webservers
  gather_facts: yes
  become: true
  tasks:
   
    - name: Running docker image as a container
      command: docker run -d --name myproj -p 8888:8080 anjidockerid/first_docker_image:latest